# Generated by Django 6.0.4 on 2026-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekskursija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200)),
                ('aprasymas', models.TextField()),
                ('vieta', models.CharField(max_length=200)),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trukme_val', models.PositiveIntegerField()),
                ('nuotrauka', models.ImageField(blank=True, null=True, upload_to='ekskursijos/')),
                ('aktyvi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ekskursijos',
            },
        ),
    ]
