# Generated by Django 6.0.4 on 2026-05-19 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('temperature_threshold', models.IntegerField()),
                ('temperature_comparison', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('equal', 'Equal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('importance', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pupils', models.ManyToManyField(related_name='collection_routes', through='ekskursijos.Collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='ekskursijos.collectionroute'),
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('excursion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('itinerary_ready', 'Itinerary Ready'), ('route_ready', 'Route Ready'), ('published', 'Published')], default='created', max_length=20)),
                ('clothing_items', models.ManyToManyField(blank=True, related_name='excursions', to='ekskursijos.clothing')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_routes', to='ekskursijos.excursion'),
        ),
        migrations.CreateModel(
            name='ListOfPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('excursion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_places', to='ekskursijos.excursion')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAddressProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('is_obligatory', models.BooleanField(default=False)),
                ('list_of_places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_progresses', to='ekskursijos.listofplaces')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_progresses', to='ekskursijos.place')),
            ],
            options={
                'unique_together': {('list_of_places', 'place')},
            },
        ),
        migrations.AddField(
            model_name='listofplaces',
            name='places',
            field=models.ManyToManyField(related_name='lists', through='ekskursijos.ObjectAddressProgress', to='ekskursijos.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.ManyToManyField(blank=True, related_name='places', to='ekskursijos.placetype'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place_types', models.ManyToManyField(blank=True, related_name='genres', to='ekskursijos.placetype')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('excursion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='ekskursijos.excursion')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_genres', to='ekskursijos.genre')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_genres', to='ekskursijos.playlist')),
                ('voted_pupils', models.ManyToManyField(blank=True, related_name='voted_playlist_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('teacher', 'Teacher'), ('pupil', 'Pupil')], max_length=20)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('genres', models.ManyToManyField(blank=True, related_name='songs', to='ekskursijos.genre')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('route', 'pupil')},
        ),
        migrations.CreateModel(
            name='ExcursionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('participating', 'Participating'), ('not_participating', 'Not Participating'), ('not_chosen', 'Not Chosen')], default='not_chosen', max_length=20)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='ekskursijos.excursion')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pupil', 'excursion')},
            },
        ),
        migrations.CreateModel(
            name='GenrePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_genre_prices', to='ekskursijos.genre')),
                ('first_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_genre_prices', to='ekskursijos.genre')),
            ],
            options={
                'unique_together': {('first_genre', 'final_genre')},
            },
        ),
        migrations.CreateModel(
            name='PupilBackpackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('taken', models.BooleanField(default=False)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_backpack_items', to='ekskursijos.excursion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_backpack_items', to='ekskursijos.item')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backpack_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pupil', 'excursion', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SharedBackpackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_backpack_items', to='ekskursijos.excursion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_backpack_items', to='ekskursijos.item')),
            ],
            options={
                'unique_together': {('excursion', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ekskursijos.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='ekskursijos.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TypesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('first_place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_prices', to='ekskursijos.placetype')),
                ('second_place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_prices', to='ekskursijos.placetype')),
            ],
            options={
                'unique_together': {('first_place_type', 'second_place_type')},
            },
        ),
    ]
