# Generated by Django 6.0.4 on 2026-04-16 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskursijos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ekskursija',
            name='ekskursijos_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ekskursija',
            name='statusas',
            field=models.CharField(choices=[('sukurta', 'Sukurta ekskursija'), ('objektai', 'Sudarytas objektų sąrašas'), ('marsrutas', 'Sudarytas maršrutas'), ('paskelbta', 'Paskelbta ekskursija')], default='sukurta', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mokytojas', 'Mokytojas'), ('mokinys', 'Mokinys')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EkskursijosDalyvavimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusas', models.CharField(choices=[('dalyvauja', 'Dalyvauja'), ('nedalyvauja', 'Nedalyvauja'), ('nepasirinko', 'Nepasirinko')], default='nepasirinko', max_length=20)),
                ('ekskursija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekskursijos.ekskursija')),
                ('mokinys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mokinys', 'ekskursija')},
            },
        ),
    ]
