# Generated by Django 6.0.4 on 2026-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskursijos', '0002_ekskursija_ekskursijos_data_ekskursija_statusas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekskursija',
            name='aktyvi',
        ),
        migrations.RemoveField(
            model_name='ekskursija',
            name='aprasymas',
        ),
        migrations.RemoveField(
            model_name='ekskursija',
            name='kaina',
        ),
        migrations.RemoveField(
            model_name='ekskursija',
            name='nuotrauka',
        ),
        migrations.RemoveField(
            model_name='ekskursija',
            name='trukme_val',
        ),
        migrations.RemoveField(
            model_name='ekskursija',
            name='vieta',
        ),
        migrations.AddField(
            model_name='ekskursija',
            name='pabaigos_laikas',
            field=models.DateField(default='2027-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekskursija',
            name='pradžios_laikas',
            field=models.DateField(default='2026-12-30'),
            preserve_default=False,
        ),
    ]
