# Generated by Django 6.0.4 on 2026-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskursijos', '0003_remove_ekskursija_aktyvi_remove_ekskursija_aprasymas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekskursija',
            name='ekskursijos_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ekskursija',
            name='pabaigos_laikas',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ekskursija',
            name='pradžios_laikas',
            field=models.TimeField(),
        ),
    ]
