# Generated by Django 6.0.4 on 2026-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekskursijos', '0004_alter_ekskursija_ekskursijos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekskursija',
            name='ekskursijos_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
